name: Generate Keystore

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:

      - name: Generate keystore
        run: |
          keytool -genkey -v \
            -keystore my.keystore \
            -alias problemcode \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=Alisha, OU=Dev, O=ProblemCode, L=City, S=State, C=US" \
            -storepass alisha123 \
            -keypass alisha123

      - name: Convert to base64
        run: base64 -w 0 my.keystore > keystore_base64.txt

      - name: Print base64 value
        run: cat keystore_base64.txt

      - name: Upload keystore as artifact
        uses: actions/upload-artifact@v4
        with:
          name: keystore-files
          path: |
            my.keystore
            keystore_base64.txt
          retention-days: 1
